# Generated by Django 4.0.1 on 2022-01-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakeapi', '0002_alter_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
