# Generated by Django 4.0.4 on 2022-05-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk_link', models.CharField(blank=True, max_length=60, verbose_name='Vkontakte')),
                ('instagram_link', models.CharField(blank=True, max_length=60, verbose_name='Instagram')),
                ('telegram_link', models.CharField(blank=True, max_length=60, verbose_name='Telegram')),
                ('whatsapp_link', models.CharField(blank=True, max_length=60, verbose_name='Whatsapp')),
                ('viber_link', models.CharField(blank=True, max_length=60, verbose_name='Viber')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='WorkingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.CharField(help_text='пн. — пт. с 9:00 до 17:30', max_length=120, verbose_name='Время работы')),
                ('delivery_days', models.CharField(help_text='пн. — пт. с 12:00 до 17:00', max_length=120, verbose_name='Время доставки')),
                ('working_years', models.CharField(default='2021', max_length=20, verbose_name='Года работы магазина')),
                ('shop_address', models.CharField(blank=True, max_length=60, verbose_name='Адрес магазина')),
            ],
            options={
                'verbose_name': 'Данные о работе',
                'verbose_name_plural': 'Данные о работе',
            },
        ),
    ]
