# Generated by Django 4.0.1 on 2022-03-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=60, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=60, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='viber_link',
            field=models.CharField(blank=True, max_length=60, verbose_name='Viber'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='vk_link',
            field=models.CharField(blank=True, max_length=60, verbose_name='Vkontakte'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='whatsapp_link',
            field=models.CharField(blank=True, max_length=60, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='workinginfo',
            name='shop_address',
            field=models.CharField(blank=True, max_length=60, verbose_name='Адрес магазина'),
        ),
    ]
