# Generated by Django 4.0.4 on 2022-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='shipping_addresses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=155, verbose_name='Адрес'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
