# Generated by Django 4.0.1 on 2022-03-09 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersocket',
            name='depth',
            field=models.IntegerField(default=0, verbose_name='Глубина'),
        ),
        migrations.AddField(
            model_name='computersocket',
            name='height',
            field=models.IntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='computersocket',
            name='width',
            field=models.IntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
