# Generated by Django 4.0.4 on 2022-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='type_of',
            field=models.CharField(default='socket', max_length=60),
        ),
    ]
