# Generated by Django 4.0.1 on 2022-02-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='collection_images', verbose_name='Изображение')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='shop.collection')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
