# Generated by Django 4.0.1 on 2022-02-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_collectioncolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncolor',
            name='color_code',
            field=models.CharField(default='#fff', max_length=60, verbose_name='Код цвета'),
        ),
    ]
