# Generated by Django 4.0.1 on 2022-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_computersocket_type_of_dimmer_type_of_frame_type_of_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstlevelcategory',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='second_level_category', to='shop.SecondLevelCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='secondlevelcategory',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='third_level_category', to='shop.ThirdLevelCategory', verbose_name='Категория'),
        ),
    ]
