# Generated by Django 4.0.1 on 2022-02-02 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_collectioncolor_color_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectionImage',
        ),
    ]
