# Generated by Django 4.0.1 on 2022-03-09 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_socket_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AlterField(
            model_name='socket',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sockets', to='shop.collection', verbose_name='Коллекция'),
        ),
    ]
