# Generated by Django 4.0.1 on 2022-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_firstlevelcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersocket',
            name='type_of',
            field=models.CharField(default='computer-socket', max_length=60),
        ),
        migrations.AlterField(
            model_name='networkfilter',
            name='type_of',
            field=models.CharField(default='network-filter', max_length=60),
        ),
    ]
