# Generated by Django 4.0.4 on 2022-05-24 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_firstlevelcategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersocket',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='dimmer',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='frame',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='networkfilter',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='plug',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='socket',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='switch',
            name='type_of',
        ),
        migrations.RemoveField(
            model_name='thermostat',
            name='type_of',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
