# Generated by Django 4.0.4 on 2022-05-24 09:19

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_computersocket_type_of_remove_dimmer_type_of_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectioncolor',
            old_name='collection',
            new_name='Collection',
        ),
        migrations.RemoveField(
            model_name='collectioncolor',
            name='color_code',
        ),
        migrations.AlterField(
            model_name='collectioncolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='computersocket',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='dimmer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='frame',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='networkfilter',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='plug',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='socket',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand', verbose_name='Производитель'),
        ),
    ]
