# Generated by Django 4.0.1 on 2022-03-09 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_switch_collection_alter_socket_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersocket',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computer_sockets', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='dimmer',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dimmers', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='frame',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frames', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='networkfilter',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_filters', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='plug',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plugs', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thermostats', to='shop.collection', verbose_name='Коллекция'),
        ),
    ]
