# Generated by Django 4.0.1 on 2022-02-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_collectionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='collection_images'),
        ),
    ]
