# Generated by Django 4.0.1 on 2022-03-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_computersocket_collection_dimmer_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socket',
            name='rated_current',
            field=models.IntegerField(default=0, verbose_name='Номинальный ток, А'),
        ),
    ]
