# Generated by Django 4.0.1 on 2022-02-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_collection_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='manufacturer',
            field=models.CharField(default='Schneider Electric', max_length=60, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='collectioncolor',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.collection', verbose_name='Коллекция'),
        ),
        migrations.AddField(
            model_name='collection',
            name='coolection_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='shop.collectionoffer', verbose_name='Предложение'),
        ),
    ]
