# Generated by Django 4.0.1 on 2022-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_collectionoffer_collection_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='collection_images', verbose_name='Изображение'),
        ),
    ]
