# Generated by Django 4.0.1 on 2022-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_socket_rated_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersocket',
            name='rated_current',
            field=models.IntegerField(default=0, verbose_name='Номинальный ток, А'),
        ),
        migrations.AlterField(
            model_name='switch',
            name='rated_current',
            field=models.IntegerField(default=0, verbose_name='Номинальный ток, А'),
        ),
    ]
