# Generated by Django 4.0.4 on 2022-06-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_computersocket_favourite_dimmer_favourite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computersocket',
            options={'verbose_name': 'Компьютерная розетка', 'verbose_name_plural': 'Компьютерные розетки'},
        ),
        migrations.AlterModelOptions(
            name='dimmer',
            options={'verbose_name': 'Диммер', 'verbose_name_plural': 'Диммеры'},
        ),
        migrations.AlterModelOptions(
            name='frame',
            options={'verbose_name': 'Рамка', 'verbose_name_plural': 'Рамки'},
        ),
        migrations.AlterModelOptions(
            name='networkfilter',
            options={'verbose_name': 'Сетевой фильтр', 'verbose_name_plural': 'Сетевые фильтры'},
        ),
        migrations.AlterModelOptions(
            name='plug',
            options={'verbose_name': 'Заглушка', 'verbose_name_plural': 'Заглушки'},
        ),
        migrations.AlterModelOptions(
            name='socket',
            options={'verbose_name': 'Розетка', 'verbose_name_plural': 'Розетки'},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'verbose_name': 'Переключатель', 'verbose_name_plural': 'Переключатели'},
        ),
        migrations.AlterModelOptions(
            name='thermostat',
            options={'verbose_name': 'Терморегулятор', 'verbose_name_plural': 'Терморегуляторы'},
        ),
    ]
