# Generated by Django 4.0.1 on 2022-02-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_collection_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('socket_type', models.CharField(max_length=20, verbose_name='Тип')),
                ('montage', models.CharField(max_length=20, verbose_name='Монтаж')),
                ('terminal', models.CharField(max_length=20, verbose_name='Клемма')),
                ('rated_current', models.CharField(max_length=20, verbose_name='Номинальный ток')),
                ('socket', models.CharField(max_length=20, verbose_name='Розетка')),
                ('grounding', models.BooleanField(default=True, verbose_name='Заземление')),
                ('protection', models.CharField(max_length=20, verbose_name='Пылевлагозащищенность')),
                ('kids_protection', models.BooleanField(blank=True, verbose_name='Защита от детей')),
                ('backlight', models.BooleanField(default=False, verbose_name='Подстветка')),
                ('material', models.CharField(max_length=20, verbose_name='Материал')),
                ('equipment', models.CharField(max_length=60, verbose_name='Комплектация')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('depth', models.IntegerField(default=0, verbose_name='Глубина')),
                ('socket_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socket', to='shop.productoffer', verbose_name='Предложение')),
            ],
            options={
                'verbose_name': 'Розетка',
                'verbose_name_plural': 'Розетки',
            },
        ),
        migrations.CreateModel(
            name='SocketColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60, verbose_name='Цвет')),
                ('color_code', models.CharField(default='#fff', max_length=60, verbose_name='Код цвета')),
                ('image', models.ImageField(upload_to='collection_images', verbose_name='Изображение')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.socket', verbose_name='Розетка')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
