# Generated by Django 4.0.1 on 2022-03-11 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_computersocket_rated_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermostat',
            name='temperature_range',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Диапазон температур, °C'),
        ),
    ]
