# Generated by Django 4.0.4 on 2022-06-28 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0008_alter_computersocket_options_alter_dimmer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocketReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sockets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.socket', verbose_name='Розетки')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзыв',
                'ordering': ['created_at'],
            },
        ),
    ]
