# Generated by Django 4.0.1 on 2022-02-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_productoffer_socket_socketcolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='socket_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='socketcolor',
            name='image',
            field=models.ImageField(upload_to='socket_images', verbose_name='Изображение'),
        ),
    ]
