# Generated by Django 4.0.1 on 2022-03-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_thermostat_temperature_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermostat',
            name='adaptive_function',
            field=models.BooleanField(blank=True, default=True, verbose_name='Адаптивная функция'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='calculation_of_consumed_energy',
            field=models.BooleanField(blank=True, default=True, verbose_name='Расчет потребленной энергии'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='correction_of_sensor_readings',
            field=models.IntegerField(blank=True, default=10, verbose_name='Коррекция показаний датчика, °C'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='maximum_load_current',
            field=models.IntegerField(blank=True, default=16, verbose_name='Максимальный ток нагрузки, А'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='maximum_load_power',
            field=models.IntegerField(blank=True, default=3000, verbose_name='Максимальная мощность нагрузки, Вт'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='num_of_intervals_per_day',
            field=models.IntegerField(blank=True, default=2, verbose_name='Количество интервалов в сутки'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='num_of_programs',
            field=models.IntegerField(blank=True, default=0, verbose_name='Количество программ'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='remote_sensor_wire_length',
            field=models.IntegerField(blank=True, default=3, verbose_name='Длина провода выносного датчика, м.'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='sensor_connection_diagnostics',
            field=models.BooleanField(blank=True, default=True, verbose_name='Диагностика подключения датчика'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='temperature_hysteresis',
            field=models.FloatField(blank=True, default=0, verbose_name='Температурный гистерезис, °C'),
        ),
    ]
