# Generated by Django 4.0.1 on 2022-02-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_socket_thumbnail_alter_socketcolor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socket',
            name='socket_offer',
        ),
        migrations.DeleteModel(
            name='ProductOffer',
        ),
    ]
