# Generated by Django 4.0.1 on 2022-03-16 08:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computersocketcolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='dimmercolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='framecolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='networkfiltercolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='plugcolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='socketcolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='switchcolor',
            name='color_code',
        ),
        migrations.RemoveField(
            model_name='thermostatcolor',
            name='color_code',
        ),
        migrations.AlterField(
            model_name='computersocketcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='dimmercolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='framecolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='networkfiltercolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='plugcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='socketcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='switchcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='thermostatcolor',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default='', image_field='image', max_length=18, samples=None, verbose_name='Цвет'),
        ),
    ]
