# Generated by Django 4.0.1 on 2022-05-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_computersocketcolor_color_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название акции')),
                ('image', models.ImageField(upload_to='promotions_images', verbose_name='Изоюражение')),
                ('promotion_type', models.CharField(max_length=60, verbose_name='Тип акции')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
    ]
