# Generated by Django 4.0.1 on 2022-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_switch_alter_socket_backlight_switchcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='switch_type',
            field=models.CharField(max_length=40, verbose_name='Тип'),
        ),
    ]
