# Generated by Django 4.0.1 on 2022-02-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_frame_socket_manufacturer_switch_manufacturer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
                ('code', models.CharField(max_length=20, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('manufacturer', models.CharField(blank=True, default='Schneider Electric', max_length=60, null=True, verbose_name='Производитель')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество')),
                ('availability', models.BooleanField(default=True, verbose_name='Наличие')),
                ('plug_type', models.CharField(max_length=40, verbose_name='Тип')),
                ('montage', models.CharField(max_length=20, verbose_name='Монтаж')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='plug_images', verbose_name='Изображение')),
                ('protection', models.CharField(max_length=20, verbose_name='Пылевлагозащищенность')),
                ('backlight', models.BooleanField(default=False, verbose_name='Подсветка')),
                ('peculiarities', models.CharField(max_length=60, verbose_name='Особенности')),
                ('material', models.CharField(max_length=20, verbose_name='Материал')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина')),
                ('height', models.IntegerField(default=0, verbose_name='Высота')),
                ('depth', models.IntegerField(default=0, verbose_name='Глубина')),
            ],
            options={
                'verbose_name': 'Заглушка',
                'verbose_name_plural': 'Заглушки',
            },
        ),
        migrations.CreateModel(
            name='PlugColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=60, verbose_name='Цвет')),
                ('color_code', models.CharField(default='#fff', max_length=60, verbose_name='Код цвета')),
                ('image', models.ImageField(upload_to='plug_images', verbose_name='Изображение')),
                ('plug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.plug', verbose_name='Заглушка')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
