# Generated by Django 4.0.1 on 2022-02-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_computersocket_dimmer_networkfilter_thermostat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thermostat',
            name='adaptive_function',
            field=models.BooleanField(default=True, verbose_name='Адаптивная функция'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='calculation_of_consumed_energy',
            field=models.BooleanField(default=True, verbose_name='Расчет потребленной энергии'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='correction_of_sensor_readings',
            field=models.IntegerField(default=10, verbose_name='Коррекция показаний датчика, °C'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='is_smart_home_system_device',
            field=models.BooleanField(default=False, verbose_name="Устройство системы 'Умный дом'"),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='kids_protection',
            field=models.BooleanField(default=False, verbose_name='Защита от детей'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='manual_mode',
            field=models.BooleanField(default=True, verbose_name='Ручной режим'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='maximum_load_current',
            field=models.IntegerField(default=16, verbose_name='Максимальный ток нагрузки, А'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='maximum_load_power',
            field=models.IntegerField(default=3000, verbose_name='Максимальная мощность нагрузки, Вт'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='num_of_intervals_per_day',
            field=models.IntegerField(default=2, verbose_name='Количество интервалов в сутки'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='num_of_programs',
            field=models.IntegerField(default=0, verbose_name='Количество программ'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='protection_class',
            field=models.CharField(default='IP20', max_length=20, verbose_name='Класс защиты корпуса'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='sensor_connection_diagnostics',
            field=models.BooleanField(default=True, verbose_name='Диагностика подключения датчика'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='temperature_hysteresis',
            field=models.FloatField(default=0, verbose_name='Температурный гистерезис, °C'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='wi_fi_control',
            field=models.BooleanField(blank=True, default=False, verbose_name='Управление через Wi-Fi'),
        ),
        migrations.AlterField(
            model_name='thermostat',
            name='remote_sensor_wire_length',
            field=models.IntegerField(default=3, verbose_name='Длина провода выносного датчика, м.'),
        ),
    ]
