# Generated by Django 4.0.1 on 2022-02-15 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_thermostatcolor_network_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermostatcolor',
            name='thermostat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color', to='shop.thermostat', verbose_name='Терморегулятор'),
        ),
    ]
