# Generated by Django 4.0.1 on 2022-02-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_thermostatcolor_thermostat'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkfilter',
            name='remote_control_wi_fi',
            field=models.BooleanField(default=False, verbose_name='Удаленное управление (Wi-Fi)'),
        ),
    ]
