# Generated by Django 4.0.1 on 2022-02-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_networkfilter_max_input_pulse_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkfilter',
            name='max_input_pulse_energy',
            field=models.IntegerField(default=125, verbose_name='Макс. энергия входного импульса, Дж'),
        ),
        migrations.AlterField(
            model_name='networkfilter',
            name='max_load_current',
            field=models.IntegerField(default=10, verbose_name='Макс. ток нагрузки, А'),
        ),
        migrations.AlterField(
            model_name='networkfilter',
            name='rated_current',
            field=models.IntegerField(default=220, verbose_name='Номинальное входное напряжение, В'),
        ),
    ]
