# Generated by Django 4.0.1 on 2022-02-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_networkfilter_max_input_pulse_energy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkfilter',
            name='usb_ports',
            field=models.IntegerField(default=0, verbose_name='Usb-порты'),
        ),
    ]
