# Generated by Django 4.0.1 on 2022-02-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_networkfilter_usb_ports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Предложение для товаров',
                'verbose_name_plural': 'Предложения для товаров',
            },
        ),
        migrations.AlterModelOptions(
            name='collectionoffer',
            options={'verbose_name': 'Предложение для коллекций', 'verbose_name_plural': 'Предложения для коллекций'},
        ),
        migrations.AddField(
            model_name='socket',
            name='coolection_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.productoffer', verbose_name='Предложение'),
        ),
    ]
