# Generated by Django 4.0.1 on 2022-02-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productoffer_alter_collectionoffer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socket',
            old_name='coolection_offer',
            new_name='product_offer',
        ),
    ]
