# Generated by Django 4.0.1 on 2022-02-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_rename_coolection_offer_socket_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersocket',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_sockets', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='dimmer',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimmers', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='frame',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='networkfilter',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_filters', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='plug',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugs', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='switch',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thermostats', to='shop.productoffer', verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='socket',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sockets', to='shop.productoffer', verbose_name='Предложение'),
        ),
    ]
