# Generated by Django 4.0.1 on 2022-02-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_computersocket_product_offer_dimmer_product_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sockets', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
    ]
