# Generated by Django 4.0.1 on 2022-02-25 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_socket_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersocket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computer_sockets', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='dimmer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dimmers', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='frame',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='networkfilter',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='network_filters', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='plug',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugs', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='switch',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='switches', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thermostats', to='shop.thirdlevelcategory', verbose_name='Категория'),
        ),
    ]
