# Generated by Django 4.0.1 on 2022-02-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrenPromotionsSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(upload_to='slider_images', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер акций',
                'verbose_name_plural': 'Слайдеры акций',
            },
        ),
        migrations.CreateModel(
            name='OffersSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('image', models.ImageField(upload_to='slider_images', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Слайдер предложений',
                'verbose_name_plural': 'Слайдеры предложений',
            },
        ),
    ]
