# Generated by Django 4.0.4 on 2022-05-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_identificator', models.CharField(default=orders.models.generate_order_identificator, max_length=6, verbose_name='Номер заказа')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Ссылка')),
                ('payment_method', models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('Передан в доставку', 'Передан в доставку'), ('Принят в обработку', 'Принят в обработку'), ('Отменен', 'Отменен'), ('Оплачен', 'Оплачен'), ('Доставлен', 'Доставлен'), ('Создан', 'Создан'), ('Подтвержден', 'Подтвержден')], default='Создан', max_length=200, verbose_name='Статус заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('commentary', models.TextField(blank=True, max_length=500, verbose_name='Комментарий к заказу')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
