# Generated by Django 4.0.4 on 2022-05-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Передан в доставку', 'Передан в доставку'), ('Принят в обработку', 'Принят в обработку'), ('Оплачен', 'Оплачен'), ('Подтвержден', 'Подтвержден'), ('Создан', 'Создан'), ('Доставлен', 'Доставлен')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
