# Generated by Django 4.0.1 on 2022-04-11 12:40

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commentary',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_identificator',
            field=models.CharField(default=orders.models.generate_order_identificator, max_length=6),
        ),
    ]
