# Generated by Django 4.0.1 on 2022-05-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Создан', 'Создан'), ('Принят в обработку', 'Принят в обработку'), ('Подтвержден', 'Подтвержден'), ('Оплачен', 'Оплачен'), ('Передан в доставку', 'Передан в доставку'), ('Доставлен', 'Доставлен')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
