# Generated by Django 4.0.1 on 2022-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_commentary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], default='Картой', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Создан'), ('Deliveried', 'Доставлен'), ('Payed', 'Оплачен'), ('Accepted for processing', 'Принят в обработку'), ('Canceled', 'Отменен'), ('Transfered to delivery', 'Передан в доставку'), ('Accepted', 'Подтвержден')], default='Created', max_length=200),
        ),
    ]
