# Generated by Django 4.0.4 on 2022-05-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Отменен', 'Отменен'), ('Подтвержден', 'Подтвержден'), ('Передан в доставку', 'Передан в доставку'), ('Создан', 'Создан'), ('Оплачен', 'Оплачен'), ('Доставлен', 'Доставлен')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
