# Generated by Django 4.0.4 on 2022-05-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Доставлен', 'Доставлен'), ('Создан', 'Создан'), ('Оплачен', 'Оплачен'), ('Подтвержден', 'Подтвержден'), ('Принят в обработку', 'Принят в обработку'), ('Передан в доставку', 'Передан в доставку')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
