# Generated by Django 4.0.4 on 2022-05-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Подтвержден', 'Подтвержден'), ('Оплачен', 'Оплачен'), ('Доставлен', 'Доставлен'), ('Принят в обработку', 'Принят в обработку'), ('Отменен', 'Отменен'), ('Передан в доставку', 'Передан в доставку')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
