# Generated by Django 4.0.1 on 2022-04-11 12:59

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_method_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='order_identificator'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Отменен'), ('Accepted', 'Подтвержден'), ('Created', 'Создан'), ('Accepted for processing', 'Принят в обработку'), ('Deliveried', 'Доставлен'), ('Payed', 'Оплачен'), ('Transfered to delivery', 'Передан в доставку')], default='Created', max_length=200),
        ),
    ]
