# Generated by Django 4.0.1 on 2022-04-22 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_order_payment_method_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_identificator',
            field=models.CharField(default=orders.models.generate_order_identificator, max_length=6, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Принят в обработку', 'Принят в обработку'), ('Доставлен', 'Доставлен'), ('Подтвержден', 'Подтвержден'), ('Создан', 'Создан'), ('Отменен', 'Отменен'), ('Передан в доставку', 'Передан в доставку')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
    ]
