# Generated by Django 4.0.1 on 2022-04-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_order_identificator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Подтвержден', 'Подтвержден'), ('Оплачен', 'Оплачен'), ('Передан в доставку', 'Передан в доставку'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен'), ('Принят в обработку', 'Принят в обработку'), ('Создан', 'Создан')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
