# Generated by Django 4.0.4 on 2022-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят в обработку', 'Принят в обработку'), ('Отменен', 'Отменен'), ('Оплачен', 'Оплачен'), ('Передан в доставку', 'Передан в доставку'), ('Доставлен', 'Доставлен'), ('Подтвержден', 'Подтвержден'), ('Создан', 'Создан')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
