# Generated by Django 4.0.4 on 2022-06-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default='', max_length=17, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Отменен', 'Отменен'), ('Доставлен', 'Доставлен'), ('Подтвержден', 'Подтвержден'), ('Оплачен', 'Оплачен'), ('Принят в обработку', 'Принят в обработку'), ('Передан в доставку', 'Передан в доставку'), ('Создан', 'Создан')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
