# Generated by Django 4.0.1 on 2022-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method_alter_order_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Наличными', 'Наличными'), ('Картой', 'Картой')], default='Картой', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(max_length=60, unique=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Transfered to delivery', 'Передан в доставку'), ('Accepted', 'Подтвержден'), ('Created', 'Создан'), ('Payed', 'Оплачен'), ('Accepted for processing', 'Принят в обработку'), ('Canceled', 'Отменен'), ('Deliveried', 'Доставлен')], default='Created', max_length=200),
        ),
    ]
