# Generated by Django 4.0.1 on 2022-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_method_alter_order_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Подтвержден', 'Подтвержден'), ('Доставлен', 'Доставлен'), ('Отменен', 'Отменен'), ('Принят в обработку', 'Принят в обработку'), ('Передан в доставку', 'Передан в доставку'), ('Создан', 'Создан'), ('Оплачен', 'Оплачен')], default='Created', max_length=200),
        ),
    ]
