# Generated by Django 4.0.4 on 2022-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_phone_number_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Картой', 'Картой'), ('Наличными', 'Наличными')], default='Картой', max_length=200, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Отменен', 'Отменен'), ('Доставлен', 'Доставлен'), ('Создан', 'Создан'), ('Передан в доставку', 'Передан в доставку'), ('Принят в обработку', 'Принят в обработку'), ('Подтвержден', 'Подтвержден')], default='Создан', max_length=200, verbose_name='Статус заказа'),
        ),
    ]
